- name: check idenmpotency
  hosts: local  
  connection: local
  become: yes
  tasks:
  - name: user creation
    ansible.builtin.user:
      name: johnd

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ NAME }}"